Prototype of collection
vertica/VerticaPy pull request #1061
Opened 2023-12-21 14:50 UTC by jslaunwhite-microfocus

# VER-90670

This PR contains a prototype of what collecting resources as a parquet files looks like.

Key Features
* Each qprof collection activity is called a "step", broken out into its own class
* The collector iterates over steps to produce parquet files
* The collector generates a metadata.json file
* The collector bundles the metadata.json and the parquet files into a single output file
* The process is testable: each step is testable and so is the overall output

Didn't build yet, but know that we want to build
* The collect_all function should return a URL that allows the user to download files
* The collect_all function should infer a browser temp directory when using a jupyter notebook
* Better docstrings to describe the different pieces
* Continue extending tests

Next steps
* Discuss the design with everyone, ensure that we agree on the way forward
* Integrate with qprof class

2023-12-22 09:55 UTC, oualib requested changes
My comments:
1. We should create a separated folder for the collection.
2. For the information collection, we do not need to work with steps but more with copy of tables so 1 file for each system table. For the version, or other "small info" we can merge them together in one file or just create one PARQUET file for each.
3. Look why your tests are failing.

2023-12-22 09:55 UTC, oualib commented on verticapy/performance/vertica/__init__.py
> +from verticapy.performance.vertica.step00_vertica_version import Step00VerticaVersion
I really don't like the name, will we create a file for each step? I don't think we will even implement all of them.

2023-12-22 09:55 UTC, oualib commented on verticapy/performance/vertica/collection_metadata.py
> +"""
should it be in another folder named "collection" and we can then rename this file metadata.py?

2023-12-22 14:55 UTC, jslaunwhite-microfocus commented
>     1. We should create a separated folder for the collection.

Which folder would you prefer? `performance/vertica/collection?`
 
>     2. For the information collection, we do not need to work with steps but more with copy of tables so 1 file for each system table. For the version, or other "small info" we can merge them together in one file or just create one PARQUET file for each.

I agree with part of the statement above. 
- Yes, I think we can decouple some of the collection from the analysis, and just collect a few of the tables. 
- And yes, it is better to merge some of the info into a single table.
- Do we want to support "offline" analysis? For this small data, we could support analysis from the parquet files without load into a DB. It makes things easier for users. But I'm not sure if that is something to prioritize.
- I want to break the qprof steps into pieces. There's a few ways to do that.... we should discuss.

>     3. Look why your tests are failing.

All legs of the test timed out, including test legs that didn't have a new test from me. I don't have a button to resubmit tests on the same commit. Is there somewhere I can re-run tests? I am also unable to add reviewers... perhaps I need more permissions?

2023-12-27 18:05 UTC, oualib commented
I am closing this PR as we've changed our direction for the collection.

2023-12-27 18:05 UTC, closed without merging

2023-12-28 12:00 UTC, jslaunwhite-microfocus commented
Correct! This PR should be closed because we have a different direction for collection