Qprof Interface Update + format_query
vertica/VerticaPy pull request #1173
Opened 2024-02-27 18:32 UTC by mail4umar

made the following changes to QueryProfielrInterface.get_qplan_tree;

- Added theQuery Execution Time for each query
- Added a display of the Query 

Also fixed format_query:

Previously there was no way to fetch the html representation of a formatted query if you don't print it. I updated it such that this can now give the html without printing:

```
format_query(query, print_sql=False)
```

2024-02-27 20:08 UTC, roypaulin commented
![image](https://github.com/vertica/VerticaPy/assets/55731470/51749fc9-cb7a-4919-be10-ca38507aca14)

This is what it looks like. I don't like this approach because:
  - If the query is long, it won't fit in that space
  - If in the feature we add more settings, there will be even less space for execution time + query
  - The style(width, margin, padding, alignment etc,...) is not consistent
I think the settings box should only contain settings info and not display anything.
I have a few ideas about how we can do this and I can share them with you when you have time.

2024-02-27 20:15 UTC, oualib commented
> ![image](https://private-user-images.githubusercontent.com/55731470/308319095-51749fc9-cb7a-4919-be10-ca38507aca14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjUxNjcsIm5iZiI6MTcwOTA2NDg2NywicGF0aCI6Ii81NTczMTQ3MC8zMDgzMTkwOTUtNTE3NDlmYzktY2I3YS00OTE5LWJlMTAtY2EzODUwN2FjYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDIwMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGM4MjE5ZTE5YzgyYjRmZWQxODk3OTgxYmVkMmZmYjI5MDA0YjMyM2RlN2Y3NWVlMzhkYWE1MzQ1ZDI1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_jpVcDzvU_538GMpxySTB7wVH6bcOMk3Gq6kiUqk4Y)
> 
> This is what it looks like. I don't like this approach because:
> 
> * If the query is long, it won't fit in that space
> * If in the feature we add more settings, there will be even less space for execution time + query
> * The style(width, margin, padding, alignment etc,...) is not consistent
>   I think the settings box should only contain settings info and not display anything.
>   I have a few ideas about how we can do this and I can share them with you when you have time.

I think it is a good solution at the moment, and you can then improve it later?

2024-02-27 21:57 UTC, roypaulin commented
> > ![image](https://private-user-images.githubusercontent.com/55731470/308319095-51749fc9-cb7a-4919-be10-ca38507aca14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjUxNjcsIm5iZiI6MTcwOTA2NDg2NywicGF0aCI6Ii81NTczMTQ3MC8zMDgzMTkwOTUtNTE3NDlmYzktY2I3YS00OTE5LWJlMTAtY2EzODUwN2FjYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDIwMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGM4MjE5ZTE5YzgyYjRmZWQxODk3OTgxYmVkMmZmYjI5MDA0YjMyM2RlN2Y3NWVlMzhkYWE1MzQ1ZDI1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_jpVcDzvU_538GMpxySTB7wVH6bcOMk3Gq6kiUqk4Y)
> > This is what it looks like. I don't like this approach because:
> > 
> > * If the query is long, it won't fit in that space
> > * If in the feature we add more settings, there will be even less space for execution time + query
> > * The style(width, margin, padding, alignment etc,...) is not consistent
> >   I think the settings box should only contain settings info and not display anything.
> >   I have a few ideas about how we can do this and I can share them with you when you have time.
> 
> I think it is a good solution at the moment, and you can then improve it later?

I am not asking to do everything on this ticket but to at least make something that would be easy to improve. If later there is not enough space and we have to move those widgets, it will take more effort.
But if right now displaying the execution time + query is the AC then yes this is good enough

2024-02-28 07:15 UTC, oualib requested changes
Your changes on the format files make the overall tests bugging... Those functions are really sensitive...

2024-02-28 12:48 UTC, mail4umar commented
> > > ![image](https://private-user-images.githubusercontent.com/55731470/308319095-51749fc9-cb7a-4919-be10-ca38507aca14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjUxNjcsIm5iZiI6MTcwOTA2NDg2NywicGF0aCI6Ii81NTczMTQ3MC8zMDgzMTkwOTUtNTE3NDlmYzktY2I3YS00OTE5LWJlMTAtY2EzODUwN2FjYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDIwMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGM4MjE5ZTE5YzgyYjRmZWQxODk3OTgxYmVkMmZmYjI5MDA0YjMyM2RlN2Y3NWVlMzhkYWE1MzQ1ZDI1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_jpVcDzvU_538GMpxySTB7wVH6bcOMk3Gq6kiUqk4Y)
> > > This is what it looks like. I don't like this approach because:
> > > 
> > > * If the query is long, it won't fit in that space
> > > * If in the feature we add more settings, there will be even less space for execution time + query
> > > * The style(width, margin, padding, alignment etc,...) is not consistent
> > >   I think the settings box should only contain settings info and not display anything.
> > >   I have a few ideas about how we can do this and I can share them with you when you have time.
> > 
> > 
> > I think it is a good solution at the moment, and you can then improve it later?
> 
> I am not asking to do everything on this ticket but to at least make something that would be easy to improve. If later there is not enough space and we have to move those widgets, it will take more effort. But if right now displaying the execution time + query is the AC then yes this is good enough

@roypaulin , i added an overflow so that when the query is longer, we get a scroll bar. We can control the size of query/overflow conveniently.

2024-02-28 12:54 UTC, roypaulin commented
> > > > ![image](https://private-user-images.githubusercontent.com/55731470/308319095-51749fc9-cb7a-4919-be10-ca38507aca14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNjUxNjcsIm5iZiI6MTcwOTA2NDg2NywicGF0aCI6Ii81NTczMTQ3MC8zMDgzMTkwOTUtNTE3NDlmYzktY2I3YS00OTE5LWJlMTAtY2EzODUwN2FjYTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDIwMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZGM4MjE5ZTE5YzgyYjRmZWQxODk3OTgxYmVkMmZmYjI5MDA0YjMyM2RlN2Y3NWVlMzhkYWE1MzQ1ZDI1MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o_jpVcDzvU_538GMpxySTB7wVH6bcOMk3Gq6kiUqk4Y)
> > > > This is what it looks like. I don't like this approach because:
> > > > 
> > > > * If the query is long, it won't fit in that space
> > > > * If in the feature we add more settings, there will be even less space for execution time + query
> > > > * The style(width, margin, padding, alignment etc,...) is not consistent
> > > >   I think the settings box should only contain settings info and not display anything.
> > > >   I have a few ideas about how we can do this and I can share them with you when you have time.
> > > 
> > > 
> > > I think it is a good solution at the moment, and you can then improve it later?
> > 
> > 
> > I am not asking to do everything on this ticket but to at least make something that would be easy to improve. If later there is not enough space and we have to move those widgets, it will take more effort. But if right now displaying the execution time + query is the AC then yes this is good enough
> 
> @roypaulin , i added an overflow so that when the query is longer, we get a scroll bar. We can control the size of query/overflow conveniently.

Can you show me an image with a long query where overflow is applied?

2024-02-28 12:55 UTC, roypaulin commented
The query header is too big.

2024-02-28 13:03 UTC, mail4umar commented
> The query header is too big.

I agree. We can decrease that considering the utilization of the space.

2024-02-28 17:05 UTC, mail4umar commented
> Your changes on the format files make the overall tests bugging... Those functions are really sensitive...

I updated it such that the old functionality remains and another one is added.

2024-02-28 17:11 UTC, roypaulin approved these changes

2024-02-29 16:57 UTC, oualib approved these changes

2024-02-29 18:55 UTC, merged