plotly integration - horizontal bar chart
vertica/VerticaPy pull request #504
Opened 2023-03-16 19:07 UTC by mail4umar

- added code for 1d horizontal bar chart
- added unit test

2023-03-16 20:05 UTC, oualib requested changes

2023-03-16 20:05 UTC, oualib commented on verticapy/plotting/_plotly/barh.py
> +            "xaxis_title": "density",
same than the other PR.

2023-03-17 13:45 UTC, mail4umar commented on verticapy/plotting/_plotly/barh.py
> +            "xaxis_title": "density",
done

2023-03-17 15:15 UTC, oualib approved these changes

2023-03-17 15:15 UTC, merged