Unit testing regression metrics
vertica/VerticaPy pull request #601
Opened 2023-05-11 16:04 UTC by vikash018

to - @mail4umar @VerticaDataScientist 

cc - @oualib 

Please review it. I have put comments in testcases for mismatches and clarifications.

2023-05-11 16:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vertica/VerticaPy?pullRequest=601) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vertica/VerticaPy?pullRequest=601) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vertica/VerticaPy?pullRequest=601) it.</sub>

2023-05-12 20:08 UTC, mail4umar commented on verticapy/tests_new/machine_learning/metrics/test_regression_metrics.py
> +        # ******************************** verticapy logic ***************************************
You can create two separate functions for better readability.

2023-05-15 16:09 UTC, mail4umar approved these changes

2023-06-05 11:12 UTC, oualib commented
@mail4umar can you please check carefully this PR? It seems @vikash018 is modifying some of your plotting files.

2023-06-05 11:12 UTC, oualib commented
@vikash018 please always add the right label to the PR.

2023-06-05 11:15 UTC, oualib requested changes
@mail4umar please triple check this PR

2023-06-05 14:12 UTC, mail4umar commented on verticapy/plotting/_plotly/machine_learning/logistic_reg.py
I think you have an older version of this function. plz revert these changes for this file "logistic_reg.py"

2023-06-05 14:13 UTC, mail4umar commented on verticapy/tests_new/conftest.py
plz check if you have applied black here. the lines seem long.

2023-06-07 11:49 UTC, oualib approved these changes

2023-06-07 11:49 UTC, oualib commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
why Github had detected some changes on this file whereas I see none?

2023-06-07 12:03 UTC, vikash018 commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
I guess, Initially there were few tests added to this file. I removed it as we have separate branch for classification metrics - unit test - 578-unit-testing-classification-metrics.

2023-06-07 12:04 UTC, oualib commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
can you please find a way to remove this file from the PR so we can merge?

2023-06-07 12:14 UTC, vikash018 commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
sure. I can delete this file (in local) and commit to this branch.

2023-06-07 15:15 UTC, oualib commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
where is the classification metrics file? I don't see it in the main repo

2023-06-07 15:26 UTC, vikash018 commented on verticapy/tests_new/machine_learning/metrics/test_classification_metrics.py
I could see - https://github.com/vertica/VerticaPy/tree/unit-testing-regression-metrics/verticapy/machine_learning/metrics

2023-06-07 16:44 UTC, merged