docstring changes for memmodel/preprocessing
vertica/VerticaPy pull request #791
Opened 2023-10-30 17:21 UTC by abhsharma2

2023-10-30 18:41 UTC, oualib approved these changes
approve, I'll quickly resolve the small issues.

2023-10-30 18:41 UTC, oualib commented on verticapy/machine_learning/memmodel/preprocessing.py
> +        and 'maximum' values of feature(S) defines a MinMaxScaler model.
please change the sentence:
... 'maximum' values of the different features define a ...

2023-10-30 18:41 UTC, oualib commented on verticapy/machine_learning/memmodel/preprocessing.py
> +    A MinMaxScaler model is defined by minimum and maximum values. In this example, we will use the following:
sentence is too long, please try to go back to line when it is the case.

2023-10-30 18:41 UTC, oualib commented on verticapy/machine_learning/memmodel/preprocessing.py
> +    A MinMaxScaler model is defined by minimum and maximum values. In this example, we will use the following:
same below

2023-10-30 19:01 UTC, mail4umar requested changes

2023-10-30 19:01 UTC, mail4umar commented on verticapy/machine_learning/memmodel/preprocessing.py
> +        model_ohe = OneHotEncoder(categories, drop_first, column_naming)
for consistency and ease of users to copy, can you combine it into one block i.e

``` 
model = OneHotEncoder(
        categories = categories,
        drop_first = False,
        column_naming = "values"
)

```

2023-10-30 19:16 UTC, oualib commented on verticapy/machine_learning/memmodel/preprocessing.py
> +    .. ipython:: python
it would be hard for this example

2023-10-31 02:15 UTC, mail4umar approved these changes

2023-10-31 02:15 UTC, mail4umar commented
> @mail4umar everything is updated, try to look at the render on your end.

all looks good! you can merge when tests pass.

2023-10-31 02:30 UTC, merged